## Genrerating realistic fake database using `FAKER` librabry

In [1]:
import pandas as pd 
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker('en_IN') # Use Indian locale for realistic data

In [2]:
mumbai_areas = ['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Ghatkopar', 'Juhu', 'Kurla', 'Malad', 'Mulund', 'Powai', 'Santacruz', 'Vile Parle']
car_types = ['Sedan', 'SUV', 'Hatchback']
fuel_types = ['Petrol', 'Diesel', 'Electric', 'Hybrid']
ac_types = ["Ac", "Non-Ac"]
ride_status = ["Completed", "Completed", "Completed", "Completed", "Cancelled"] # 80% completed, 20% cancelled

In [3]:
'''print(f"Mumbai Areas: {mumbai_areas}")
print(f"Car Types: {car_types}")
print(f"Fuel Types: {fuel_types}")
print(f"AC Types: {ac_types}")
print(f"Ride Status: {ride_status}")
print(f"Vehicle Models: {vehicle_models}")'''

'print(f"Mumbai Areas: {mumbai_areas}")\nprint(f"Car Types: {car_types}")\nprint(f"Fuel Types: {fuel_types}")\nprint(f"AC Types: {ac_types}")\nprint(f"Ride Status: {ride_status}")\nprint(f"Vehicle Models: {vehicle_models}")'

# Pay by car type and base pay

In [4]:
fare_rates = {
  "Sedan" : 15,
  "SUV" : 19,
  "Hatchback" : 11
}
base_fare = 50

## Data from past 1 year

In [5]:
end_date = datetime.now()
start_date = end_date - timedelta(days=365) # Last 1 year

print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")

Start Date: 2025-06-01 19:32:56.042418
End Date: 2026-06-01 19:32:56.042418

## Generating and storing unique Licence plate numbeer

In [6]:
import pandas as pd 
import random
import string 
import time 

start_rand_plate_num = time.time()
used_numbers = set()       #  set  → validation / lookup (fast checking)
plates = []                   # list → storage / ordering (ordered storage)

def license_plate_generator():
    state = 'MH' # Maharashtra state code for license plates
    district_code = random.randint(1, 50) # Random district code between 1 and 50

    letters = string.ascii_uppercase # Uppercase letters for license plate
    char = ''.join(random.choices(letters, k=2)) # Random 2 letters for license plate

    numeric_part = f"{random.randint(0, 9999):04d}" # Random 4 digit number for license plate, formated 04d means fill empty space with 0 and generate 4 digit number d means integer
    return f"{state}{district_code} {char} {numeric_part}"

end_rand_plate_num = time.time()

start_unique_plate = time.time()

def generate_unique_license_plate():
    while True:
        license_plate = license_plate_generator()
        if license_plate not in used_numbers:
            used_numbers.add(license_plate)
            plates.append(license_plate)        # just to create a list to check

            return license_plate

for i in range(10000):
        vehicle_license_plate = generate_unique_license_plate()
        
end_unique_plate = time.time()

print(f"Random plate generated : {end_rand_plate_num - start_rand_plate_num:.2}") 
time.sleep(1)
print(f"Unique plate identified and stored: {end_unique_plate - start_unique_plate:.2}\n")
time.sleep(1)

print(f"Generated License Plate: {vehicle_license_plate}")
time.sleep(1)
print(f"Unique plate numbers: {(plates)[-5:]}")        # last 5 plate numbers
time.sleep(1)
print(f"Total num of unique plates generated: {len(used_numbers)} ")
time.sleep(1)

df = pd.DataFrame

Random plate generated : 0.0
Unique plate identified and stored: 0.029

Generated License Plate: MH26 WU 6462
Unique plate numbers: ['MH18 BO 9936', 'MH21 OA 3344', 'MH18 II 6744', 'MH4 SA 2092', 'MH26 WU 6462']
Total num of unique plates generated: 10000

In [7]:
print(len(vehicle_license_plate)) # counts the characte of the plates

12

# Generating 10000 unique drivers data

In [8]:
vehicle_category = {

    "Hyundai Creta": "SUV",

    "Tata Nexon": "SUV",

    "Honda City": "Sedan",

    "Swift Dzire": "Sedan",

    "WagonR": "Hatchback",

    "Toyota Innova": "SUV"
}

# idempotency
Running the same code multiple times should not corrupt or change existing valid data.

In [9]:
import pandas as pd 
import random 
from faker import Faker 
import time

faker = Faker('en_IN')  

# idempotency
import os

if not os.path.exists("../data/drivers.csv"):   # Check if file exists if yes True ---> Fale (reverse result)
    print("Generating new drivers...")
    
    driver_info = []
    letters = 'DRV'

    def drivers_data(driver_num):
        vehical_model = random.choice(list(vehicle_category.keys()))
        joining_date = pd.Timestamp('2011-01-01')
        current_date = datetime.now()
        driver_info.append({
            "driver_id" : f"{letters}{driver_num+1:05d}",
            "driver_name" : faker.name(),
            "driver_phone": faker.phone_number(),
            "driver_age": random.randint(18,70),
            "driver_address": f"Flat {random.randint(1,500)}, {random.choice(mumbai_areas)}",
            "registration_date": faker.date_time_between(joining_date, current_date),
            "license_plate" : plates[driver_num],
            "driver_vehicle_model": vehical_model,  
            "car_type": vehicle_category[vehical_model],        # dictonary lookup
            "driver_rating": round(random.uniform(3.5, 5.0), 1), # Rating between 3.5 and 5.0
            "driver_experience_years": random.randint(1, 20), # Experience between 1 and 20 years
        })

    for driver_num in range(10000):
        drivers_data(driver_num)

    df = pd.DataFrame(driver_info)
    df.index = range(1,len(df) + 1)

    df.to_csv("../data/drivers.csv" , sep = ",", index=False )

else:
    print("Drivers already exist")
    df = pd.read_csv("../data/drivers.csv")
df

Drivers already exist

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
0,DRV00001,Jagvi Puri,911933805437,69,"Flat 400, Kurla",2013-08-06 05:00:01,MH7 UV 1817,Hyundai Creta,SUV,4.4,6
1,DRV00002,Udant Anne,918746187195,56,"Flat 127, Andheri",2015-07-22 02:41:19,MH42 FR 5842,Honda City,Sedan,4.8,11
2,DRV00003,Zaitra Soni,911621646909,62,"Flat 121, Santacruz",2020-11-09 00:07:20,MH16 QF 7603,Hyundai Creta,SUV,4.6,7
3,DRV00004,Anita Sur,1244233588,26,"Flat 14, Kurla",2024-06-08 14:59:33,MH10 GO 4993,Tata Nexon,SUV,4.7,12
4,DRV00005,Arin Sampath,593750170,70,"Flat 239, Bandra",2016-01-12 04:10:41,MH10 QY 1068,Honda City,Sedan,4.8,11
...,...,...,...,...,...,...,...,...,...,...,...
9995,DRV09996,Forum Nayar,912651015481,58,"Flat 32, Ghatkopar",2021-10-08 23:08:14,MH22 WT 4975,Honda City,Sedan,3.7,2
9996,DRV09997,Dalbir Viswanathan,915562628116,30,"Flat 318, Malad",2018-12-29 19:57:28,MH31 OH 0251,Hyundai Creta,SUV,3.9,15
9997,DRV09998,Lopa Balan,6543901468,41,"Flat 108, Borivali",2020-10-18 09:09:45,MH40 FJ 5489,Swift Dzire,Sedan,3.6,19
9998,DRV09999,Anay Grover,9631340583,51,"Flat 155, Juhu",2021-11-11 22:49:02,MH3 GN 5542,Hyundai Creta,SUV,4.4,15
9999,DRV10000,Vansha Atwal,629337180,66,"Flat 194, Ghatkopar",2011-05-26 15:11:04,MH44 GJ 8572,Honda City,Sedan,4.5,7

In [10]:
random_item = round(random.uniform(1, 30))
print(random_item)

7

# Sampling

List ---> Random    
DataFrame ----> Sampling

In [11]:
import random
df = pd.read_csv("../data/drivers.csv")
#Fraction sampling
df.sample(frac=0.5)         #50% data

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
9804,DRV09805,Vincent Chacko,915895147300,52,"Flat 230, Santacruz",2022-01-18 07:03:01,MH7 EP 4136,Toyota Innova,SUV,3.6,5
9087,DRV09088,Gaurangi Sankaran,8433536215,28,"Flat 184, Santacruz",2024-07-05 12:08:18,MH45 HA 9757,WagonR,Hatchback,4.5,20
3025,DRV03026,Nakul Banerjee,3929981858,56,"Flat 471, Bandra",2025-12-08 04:23:02,MH29 IV 6778,Tata Nexon,SUV,4.2,14
5015,DRV05016,Balhaar Nair,1017398115,22,"Flat 475, Vile Parle",2013-02-10 07:07:00,MH25 UX 9601,Honda City,Sedan,4.3,3
3163,DRV03164,Ekaraj Hari,5700381519,65,"Flat 353, Santacruz",2014-06-21 01:29:16,MH25 YH 8631,Tata Nexon,SUV,4.6,8
...,...,...,...,...,...,...,...,...,...,...,...
5795,DRV05796,Chakradev Dar,5179630188,45,"Flat 142, Mulund",2011-06-15 15:46:49,MH11 OS 3459,Hyundai Creta,SUV,4.3,15
5811,DRV05812,Urishilla Kannan,6954600788,69,"Flat 456, Kurla",2020-08-24 04:35:29,MH17 BS 1553,Honda City,Sedan,4.3,4
8435,DRV08436,Onveer Peri,2869935886,22,"Flat 257, Vile Parle",2022-02-16 18:01:48,MH27 EA 3242,WagonR,Hatchback,4.2,12
6103,DRV06104,Harish Chakraborty,3906018653,59,"Flat 371, Ghatkopar",2025-08-29 14:51:44,MH35 YX 1978,Honda City,Sedan,4.3,16
5518,DRV05519,Jasmit Mukhopadhyay,8610338177,42,"Flat 422, Santacruz",2016-10-28 11:54:20,MH23 OR 7619,Hyundai Creta,SUV,4.0,4

In [12]:
#Reproducible sampling    ----->  same output every run
df.sample(n=5 , random_state=42)        #the randomness seed

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
6252,DRV06253,Elijah Guha,8089482385,48,"Flat 207, Kurla",2025-03-03 06:14:51,MH32 RM 0766,Hyundai Creta,SUV,3.5,14
4684,DRV04685,Wridesh Sampath,2543039823,28,"Flat 283, Vile Parle",2012-05-11 04:37:33,MH7 ZA 1560,Tata Nexon,SUV,4.3,5
1731,DRV01732,Champak Vasa,913038023105,49,"Flat 474, Powai",2014-07-14 17:17:23,MH23 ZQ 9713,Tata Nexon,SUV,4.6,1
4742,DRV04743,Ishwar Dube,1953316561,43,"Flat 477, Dadar",2011-12-27 06:10:01,MH50 BE 1531,Tata Nexon,SUV,4.3,12
4521,DRV04522,Samar Andra,5392344535,32,"Flat 488, Powai",2012-02-11 00:52:26,MH40 YQ 5470,Hyundai Creta,SUV,4.2,4

In [13]:
import random

random.seed(2)
print(random.randint(1,10))

1

In [14]:
df.sample(n=5)

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
5009,DRV05010,Vihaan Reddy,2411171194,22,"Flat 32, Santacruz",2014-04-12 20:27:21,MH14 ZU 8941,Honda City,Sedan,3.6,7
5782,DRV05783,Ekavir Khosla,3952994441,26,"Flat 244, Malad",2022-10-14 10:07:54,MH26 OP 1509,Honda City,Sedan,3.7,8
4678,DRV04679,Yamini Cheema,3615864793,56,"Flat 379, Vile Parle",2012-03-29 20:42:36,MH46 KV 3543,Swift Dzire,Sedan,4.3,3
3343,DRV03344,Eshana Hari,1725428423,55,"Flat 245, Andheri",2018-03-07 10:57:01,MH11 BF 8704,WagonR,Hatchback,4.8,9
6851,DRV06852,Inaya Gill,919813072962,63,"Flat 245, Ghatkopar",2021-08-08 00:12:37,MH40 QC 7089,Toyota Innova,SUV,4.3,13

In [15]:
import random

df.sample(n=random.randint(1,5))

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
3446,DRV03447,Bhanumati Mitra,311245058,67,"Flat 333, Andheri",2026-03-29 16:25:02,MH43 AK 8512,WagonR,Hatchback,4.4,16

# Converting datafram sample to `dictionary`

In [16]:
df_drivers = df.sample(n=5)
df_drivers.to_dict()       # nested dictionary

'''df_drivers['driver_name'][7333]  
df_drivers['driver_name']'''
df_drivers.iloc[0].to_dict()       # ONE rows(Series)  ,  column → value

{'driver_id': 'DRV08404',
 'driver_name': 'Shivansh Ratti',
 'driver_phone': 1241427523,
 'driver_age': 28,
 'driver_address': 'Flat 125, Borivali',
 'registration_date': '2016-01-25 19:20:18',
 'license_plate': 'MH25 HI 5547',
 'driver_vehicle_model': 'WagonR',
 'car_type': 'Hatchback',
 'driver_rating': 3.9,
 'driver_experience_years': 11}

In [17]:
df_drivers.iloc[1:4].to_dict()         # MULTIPLE ds(DataFrame)----> column → {index:value}

{'driver_id': {9828: 'DRV09829', 374: 'DRV00375', 3835: 'DRV03836'},
 'driver_name': {9828: 'Ojas Pingle',
  374: 'Lakshmi Doshi',
  3835: 'Megha Chawla'},
 'driver_phone': {9828: 917213404983, 374: 5941247869, 3835: 698485021},
 'driver_age': {9828: 22, 374: 66, 3835: 48},
 'driver_address': {9828: 'Flat 391, Dadar',
  374: 'Flat 455, Vile Parle',
  3835: 'Flat 375, Malad'},
 'registration_date': {9828: '2021-11-06 23:29:26',
  374: '2018-01-25 05:20:22',
  3835: '2013-06-14 04:03:45'},
 'license_plate': {9828: 'MH5 NZ 3944',
  374: 'MH31 FQ 6276',
  3835: 'MH3 WV 1520'},
 'driver_vehicle_model': {9828: 'Swift Dzire',
  374: 'Swift Dzire',
  3835: 'Tata Nexon'},
 'car_type': {9828: 'Sedan', 374: 'Sedan', 3835: 'SUV'},
 'driver_rating': {9828: 3.9, 374: 3.5, 3835: 4.8},
 'driver_experience_years': {9828: 16, 374: 5, 3835: 19}}

In [18]:
# Why weird indexes like 7333?
# df.sample() -----> keeps original dataframe indexes.
# for clean indexing ----> row.iloc[1:4].reset_index(drop=True)  

'''import random

d = df.sample(n=5)
d.iloc[1:5].reset_index(drop=True).to_dict()'''

df_drivers.iloc[1:4].to_dict(orient="records")

[{'driver_id': 'DRV09829',
  'driver_name': 'Ojas Pingle',
  'driver_phone': 917213404983,
  'driver_age': 22,
  'driver_address': 'Flat 391, Dadar',
  'registration_date': '2021-11-06 23:29:26',
  'license_plate': 'MH5 NZ 3944',
  'driver_vehicle_model': 'Swift Dzire',
  'car_type': 'Sedan',
  'driver_rating': 3.9,
  'driver_experience_years': 16},
 {'driver_id': 'DRV00375',
  'driver_name': 'Lakshmi Doshi',
  'driver_phone': 5941247869,
  'driver_age': 66,
  'driver_address': 'Flat 455, Vile Parle',
  'registration_date': '2018-01-25 05:20:22',
  'license_plate': 'MH31 FQ 6276',
  'driver_vehicle_model': 'Swift Dzire',
  'car_type': 'Sedan',
  'driver_rating': 3.5,
  'driver_experience_years': 5},
 {'driver_id': 'DRV03836',
  'driver_name': 'Megha Chawla',
  'driver_phone': 698485021,
  'driver_age': 48,
  'driver_address': 'Flat 375, Malad',
  'registration_date': '2013-06-14 04:03:45',
  'license_plate': 'MH3 WV 1520',
  'driver_vehicle_model': 'Tata Nexon',
  'car_type': 'SUV',
  'driver_rating': 4.8,
  'driver_experience_years': 19}]

# Customer Data Generation

In [19]:
import pandas as pd
import random
import string
from faker import Faker
import time

faker = Faker('en_IN')
# idempotency
import os 

if not os.path.exists("../data/customer.csv"):
    print("Generating new customer data..")

    customer_info = []
    #char = ''.join(random.choices(letters , k=2))

    def customer_data(i):
        joining_date = pd.Timestamp("2011-01-01")
        current_date = datetime.now()
        customer_info.append({
            'customer_id': f"CUS{i+1:05d}",
            'customer_name': faker.name(),
            'customer_phone': faker.phone_number(),
            'customer_age': random.randint(18,60),
            'customer_address': f"Flat {random.randint(1,500)}, {random.choice(mumbai_areas)}",
            "registration_date": faker.date_time_between(joining_date ,current_date),
        })

    for i in range(50000):
        customer_data(i)

    df = pd.DataFrame(customer_info)
    df.index = range(1,len(df) +1)
    df.to_csv("../data/customer.csv",index=False)

else:
    print('Data already exisit.')
    df = pd.read_csv("../data/customer.csv")
df

Data already exisit.

,customer_id,customer_name,customer_phone,customer_age,customer_address,registration_date
0,CUS00001,Sai Venkataraman,8815495182,23,"Flat 185, Borivali",2017-08-08 14:06:33
1,CUS00002,George Jain,916510392481,60,"Flat 438, Ghatkopar",2011-05-24 22:18:02
2,CUS00003,Jatin Kale,2451131548,34,"Flat 311, Dadar",2011-12-23 01:27:48
3,CUS00004,Rachana Ahuja,8641317829,56,"Flat 19, Powai",2015-09-18 04:49:26
4,CUS00005,Victor Srivastava,3440792756,28,"Flat 221, Santacruz",2023-09-10 10:05:08
...,...,...,...,...,...,...
49995,CUS49996,Girik Grover,1083190568,23,"Flat 409, Bandra",2025-02-26 12:33:00
49996,CUS49997,Nandini Chander,915246214524,45,"Flat 492, Vile Parle",2023-01-09 11:56:50
49997,CUS49998,Yash Balan,915314415294,29,"Flat 233, Malad",2020-03-01 01:10:55
49998,CUS49999,Chakradhar Manne,912532810716,39,"Flat 84, Juhu",2017-12-21 17:25:13
49999,CUS50000,Anay Hora,3646653553,59,"Flat 456, Powai",2020-11-17 10:07:46

## Unsderstanding of Timestamp DateOffset , datetime timedelta

In [20]:
# Timestamp WHEN?? --> an exact point in time                                       eg 2026-05-29 18:30:00                 "ride start time/customer register time"
# Timedelta(thinks in exact units) HOW LONG???--> a duration(24 hours exactly)          eg 2 days / 3 hr / 30 min              "delivery time/exact hr min"
# DateOffset MOVE ON CALENDAR--> calendar-based movement                                     eg 1 month later / 1 year ago          "next month/previous year"
'''🚗 Important
DateOffset understands:
leap years
month lengths
calendars'''
# datetime --> basic Python date object

'''current_date = pd.Timestamp.now(tz='UTC') 
start_date = current_date - pd.DateOffset(years=1)


print(f"Start Date: {start_date}")
print(f"Current Date: {current_date}")

india_time = current_date.tz_convert("Asia/Kolkata")

print(f"India Time: {india_time}")'''

start_date = datetime.now() -  timedelta(days=7)  # Generate data for the past 7 days
end_date = datetime.now()

print(start_date)
print(end_date) 

#start = pd.Timestamp("2026-05-25 00:00:00") + pd.DateOffset(years=1) # Generate data for the future 1 year / same month last year
#now = pd.Timestamp.now()

#print(start)
#print(now)

2026-05-25 19:33:01.568021
2026-06-01 19:33:01.568021

# Rides Data Generation

In [21]:
import pandas as pd
import random
from faker import Faker
import time

faker = Faker('en_IN')

import os 

if not os.path.exists("../data/rides_data.csv"):
    print("Generating new rides data..")

    start_time = time.time()

    rides = []

    # placing these above line outside the function so that they dont decrease performance speed
    driver = pd.read_csv("../data/drivers.csv")
    customer = pd.read_csv("../data/customer.csv")

    driver_list = driver.to_dict(orient="records")
    customer_list = customer.to_dict(orient="records")

    start_date = datetime.now() - timedelta(days=365)
    end_date = datetime.now()

    def ride_generator(i):
        # drivers data in dictionary form
        driver_dict = random.choice(driver_list)
        customer_dict = random.choice(customer_list)

        distance_km = round(random.uniform(1, 30), 2) # Distance between 1 and 30 km
        car_type = driver_dict["car_type"]
        rate_per_km = fare_rates[car_type]
        total_fare = round(base_fare + rate_per_km * distance_km, 2) # Base fare + (rate per km * distance)
        
        # pickup and drop time
        pickup = faker.date_time_between(start_date , end_date)  # past 1 year time
        drop = pickup + timedelta(minutes=random.randint(20,90))    

        duration = drop - pickup
        
        # unique pickup and drop locations 
        pickup_location = random.choice(mumbai_areas)
        drop_location = random.choice(mumbai_areas)
        while pickup_location == drop_location:
            drop_location = random.choice(mumbai_areas)

        rides.append({
            'driver_id':driver_dict["driver_id"],
            'customer_id':customer_dict["customer_id"],
            'car_type': car_type,
            'pick_up_location': pickup_location,
            'drop_location': drop_location,
            'pickup_time': pickup,
            'drop_time': drop,
            'total_duration': duration.seconds //60,    
            'distance': distance_km,
            'rate_per_km': rate_per_km,
            'fare': total_fare,
            'ride_status': random.choice(['completed','completed','completed','completed','cancelled']),
        })

    for i in range(100000):
        ride_generator(i)

    end_time = time.time()

    df = pd.DataFrame(rides)
    df.index = range(1,len(df) +1)

    df.to_csv("../data/rides_data.csv", index=False)

    print(f"Data Generation Complete. {end_time - start_time}")

else:
    print("Data already exists.")
    df = pd.read_csv("../data/rides_data.csv")
df

Data already exists.

,driver_id,customer_id,car_type,pick_up_location,drop_location,pickup_time,drop_time,total_duration,distance,rate_per_km,fare,ride_status
0,DRV09703,CUS39852,SUV,Kurla,Juhu,2026-02-21 08:57:18,2026-02-21 09:22:18,25,22.48,19,477.12,completed
1,DRV02063,CUS20040,Sedan,Borivali,Andheri,2025-07-17 23:37:53,2025-07-17 23:57:53,20,12.96,15,244.40,completed
2,DRV04470,CUS19566,Hatchback,Andheri,Borivali,2025-07-12 00:38:06,2025-07-12 01:34:06,56,14.50,11,209.50,completed
3,DRV09121,CUS45208,Sedan,Kurla,Mulund,2025-09-17 11:27:38,2025-09-17 11:59:38,32,25.93,15,438.95,completed
4,DRV06672,CUS36549,SUV,Malad,Bandra,2026-04-21 05:12:36,2026-04-21 05:51:36,39,3.85,19,123.15,completed
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,DRV08275,CUS09445,Sedan,Mulund,Borivali,2026-01-29 12:50:21,2026-01-29 13:12:21,22,12.60,15,239.00,cancelled
99996,DRV09730,CUS13948,Sedan,Andheri,Ghatkopar,2026-01-10 14:04:26,2026-01-10 14:44:26,40,23.26,15,398.90,completed
99997,DRV06119,CUS45519,Sedan,Powai,Juhu,2026-04-06 13:20:19,2026-04-06 14:27:19,67,25.08,15,426.20,completed
99998,DRV07716,CUS08354,Sedan,Kurla,Mulund,2025-06-14 06:34:26,2025-06-14 07:03:26,29,29.01,15,485.15,completed
99999,DRV08980,CUS00221,Sedan,Kurla,Borivali,2026-05-09 02:13:29,2026-05-09 03:38:29,85,2.06,15,80.90,completed

In [22]:
# for HH:MM:SS data " ".join(str(duration).split(" "))

In [24]:
df = pd.read_csv("../data/drivers.csv")
df

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
0,DRV00001,Jagvi Puri,911933805437,69,"Flat 400, Kurla",2013-08-06 05:00:01,MH7 UV 1817,Hyundai Creta,SUV,4.4,6
1,DRV00002,Udant Anne,918746187195,56,"Flat 127, Andheri",2015-07-22 02:41:19,MH42 FR 5842,Honda City,Sedan,4.8,11
2,DRV00003,Zaitra Soni,911621646909,62,"Flat 121, Santacruz",2020-11-09 00:07:20,MH16 QF 7603,Hyundai Creta,SUV,4.6,7
3,DRV00004,Anita Sur,1244233588,26,"Flat 14, Kurla",2024-06-08 14:59:33,MH10 GO 4993,Tata Nexon,SUV,4.7,12
4,DRV00005,Arin Sampath,593750170,70,"Flat 239, Bandra",2016-01-12 04:10:41,MH10 QY 1068,Honda City,Sedan,4.8,11
...,...,...,...,...,...,...,...,...,...,...,...
9995,DRV09996,Forum Nayar,912651015481,58,"Flat 32, Ghatkopar",2021-10-08 23:08:14,MH22 WT 4975,Honda City,Sedan,3.7,2
9996,DRV09997,Dalbir Viswanathan,915562628116,30,"Flat 318, Malad",2018-12-29 19:57:28,MH31 OH 0251,Hyundai Creta,SUV,3.9,15
9997,DRV09998,Lopa Balan,6543901468,41,"Flat 108, Borivali",2020-10-18 09:09:45,MH40 FJ 5489,Swift Dzire,Sedan,3.6,19
9998,DRV09999,Anay Grover,9631340583,51,"Flat 155, Juhu",2021-11-11 22:49:02,MH3 GN 5542,Hyundai Creta,SUV,4.4,15
9999,DRV10000,Vansha Atwal,629337180,66,"Flat 194, Ghatkopar",2011-05-26 15:11:04,MH44 GJ 8572,Honda City,Sedan,4.5,7

In [46]:
list(df.columns)

['driver_id',
 'driver_name',
 'driver_phone',
 'driver_age',
 'driver_address',
 'registration_date',
 'license_plate',
 'driver_vehicle_model',
 'car_type',
 'driver_rating',
 'driver_experience_years']

In [ ]:
class Person:

    def speak(self):
        print("Hello")

p1 = Person()

p1.speak()

Hello