## Genrerating realistic fake database using `FAKER` librabry

In [61]:
import pandas as pd 
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker('en_IN') # Use Indian locale for realistic data

In [62]:
mumbai_areas = ['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Ghatkopar', 'Juhu', 'Kurla', 'Malad', 'Mulund', 'Powai', 'Santacruz', 'Vile Parle']
car_types = ['Sedan', 'SUV', 'Hatchback']
fuel_types = ['Petrol', 'Diesel', 'Electric', 'Hybrid']
ac_types = ["Ac", "Non-Ac"]
ride_status = ["Completed", "Completed", "Completed", "Completed", "Cancelled"] # 80% completed, 20% cancelled

In [63]:
'''print(f"Mumbai Areas: {mumbai_areas}")
print(f"Car Types: {car_types}")
print(f"Fuel Types: {fuel_types}")
print(f"AC Types: {ac_types}")
print(f"Ride Status: {ride_status}")
print(f"Vehicle Models: {vehicle_models}")'''

'print(f"Mumbai Areas: {mumbai_areas}")\nprint(f"Car Types: {car_types}")\nprint(f"Fuel Types: {fuel_types}")\nprint(f"AC Types: {ac_types}")\nprint(f"Ride Status: {ride_status}")\nprint(f"Vehicle Models: {vehicle_models}")'

# Pay by car type and base pay

In [64]:
fare_rates = {
  "Sedan" : 15,
  "SUV" : 19,
  "Hatchback" : 11
}
base_fare = 50

## Data from past 1 year

In [65]:
end_date = datetime.now()
start_date = end_date - timedelta(days=365) # Last 1 year

print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")

Start Date: 2025-05-28 21:41:26.844963
End Date: 2026-05-28 21:41:26.844963

## Generating and storing unique Licence plate numbeer

In [66]:
import pandas as pd 
import random
import string 
import time 

start_rand_plate_num = time.time()
used_numbers = set()       #  set  → validation / lookup (fast checking)
plates = []                   # list → storage / ordering (ordered storage)

def license_plate_generator():
    state = 'MH' # Maharashtra state code for license plates
    district_code = random.randint(1, 50) # Random district code between 1 and 50

    letters = string.ascii_uppercase # Uppercase letters for license plate
    char = ''.join(random.choices(letters, k=2)) # Random 2 letters for license plate

    numeric_part = f"{random.randint(0, 9999):04d}" # Random 4 digit number for license plate, formated 04d means fill empty space with 0 and generate 4 digit number d means integer
    return f"{state}{district_code} {char} {numeric_part}"

end_rand_plate_num = time.time()

start_unique_plate = time.time()

def generate_unique_license_plate():
    while True:
        license_plate = license_plate_generator()
        if license_plate not in used_numbers:
            used_numbers.add(license_plate)
            plates.append(license_plate)        # just to create a list to check

            return license_plate

for i in range(10000):
        vehicle_license_plate = generate_unique_license_plate()
        
end_unique_plate = time.time()

print(f"Random plate generated : {end_rand_plate_num - start_rand_plate_num:.2}") 
time.sleep(1)
print(f"Unique plate identified and stored: {end_unique_plate - start_unique_plate:.2}\n")
time.sleep(1)

print(f"Generated License Plate: {vehicle_license_plate}")
time.sleep(1)
print(f"Unique plate numbers: {(plates)[-5:]}")        # last 5 plate numbers
time.sleep(1)
print(f"Total num of unique plates generated: {len(used_numbers)} ")
time.sleep(1)

df = pd.DataFrame

Random plate generated : 0.002
Unique plate identified and stored: 0.028

Generated License Plate: MH9 LA 6347
Unique plate numbers: ['MH18 RR 8814', 'MH23 WH 0063', 'MH48 SZ 8582', 'MH5 UC 1481', 'MH9 LA 6347']
Total num of unique plates generated: 10000

In [67]:
print(len(vehicle_license_plate)) # counts the characte of the plates

11

# Generating 10000 unique drivers data

In [68]:
vehicle_category = {

    "Hyundai Creta": "SUV",

    "Tata Nexon": "SUV",

    "Honda City": "Sedan",

    "Swift Dzire": "Sedan",

    "WagonR": "Hatchback",

    "Toyota Innova": "SUV"
}

# idempotency
Running the same code multiple times should not corrupt or change existing valid data.

In [69]:
import pandas as pd 
import random 
from faker import Faker 

faker = Faker('en_IN')  

# idempotency
import os

if not os.path.exists("../data/drivers.csv"):   # Check if file exists if yes True ---> Fale (reverse result)
    print("Generating new drivers...")
    
    driver_info = []
    letters = 'DRV'

    def drivers_data(driver_num):
        vehical_model = random.choice(list(vehicle_category.keys()))
        driver_info.append({
            "driver_id" : f"{letters}{driver_num+1:04d}",
            "driver_name" : faker.name(),
            "driver_phone": faker.phone_number(),
            "license_plate" : plates[driver_num],
            "driver_vehicle_model": vehical_model,  
            "car_type": vehicle_category[vehical_model],        # dictonary lookup
            "driver_rating": round(random.uniform(3.5, 5.0), 1), # Rating between 3.5 and 5.0
            "driver_experience_years": random.randint(1, 20), # Experience between 1 and 20 years
        })

    for driver_num in range(10000):
        drivers_data(driver_num)

    df = pd.DataFrame(driver_info)
    df.index = range(1,len(df) + 1)

    df.to_csv("../data/drivers.csv" , sep = ",", index=False )

else:
    print("Drivers already exist")
    df = pd.read_csv("../data/drivers.csv")
df

Drivers already exist

,driver_id,driver_name,driver_phone,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
0,DRV0001,Wriddhish Kala,914174649095,MH28 QB 0567,WagonR,Hatchback,4.1,1
1,DRV0002,Falan Banerjee,130098563,MH6 KT 1949,Hyundai Creta,SUV,3.8,17
2,DRV0003,Unnati Madan,919845059404,MH43 QA 8925,Tata Nexon,SUV,4.3,15
3,DRV0004,Theodore Sahni,905474949,MH19 MP 9122,WagonR,Hatchback,4.6,12
4,DRV0005,Ansh Prakash,9837727195,MH13 DK 8402,Swift Dzire,Sedan,3.9,8
...,...,...,...,...,...,...,...,...
9995,DRV9996,Faraj Sankar,934715261,MH48 IH 0880,Tata Nexon,SUV,5.0,17
9996,DRV9997,David Bains,918515090479,MH8 ML 5540,Tata Nexon,SUV,3.8,3
9997,DRV9998,Peter Palan,914560087118,MH38 QK 5963,Honda City,Sedan,3.8,16
9998,DRV9999,Yashvi Mukherjee,1928544413,MH35 OV 6249,Honda City,Sedan,4.8,2
9999,DRV10000,Widisha Sachdev,6621594408,MH23 PS 1335,Honda City,Sedan,4.8,18

In [70]:
'''import pandas as pd 
import time

overall_start_time = time.time()
ride_booking = []

def data_generator():
    car_type = random.choice(car_types)
    distance_km = round(random.uniform(1, 30), 2) # Distance between 1 and 30 km
    total_fare = round(base_fare + fare_rates[car_type] * distance_km, 2) # Base fare + (rate per km * distance)
    ride_booking.append({
        "ride_id": fake.uuid4(),
        "driver_name": fake.name(),
        "driver_phone": fake.phone_number(),
        "driver_rating": round(random.uniform(3.5, 5.0), 1), # Rating between 3.5 and 5.0
        "driver_experience_years": random.randint(1, 20), # Experience between 1 and 20 years
        "driver_vehicle_number": license_plate_generator(),
        "driver_vehicle_model": random.choice(vehicle_models),
        "customer_name": fake.name(),
        "customer_phone": fake.phone_number(),  
        "pickup_location": random.choice(mumbai_areas),
        "drop_location": random.choice(mumbai_areas),
        "car_type": car_type,
        "fuel_type": random.choice(fuel_types),
        "ac_type": random.choice(ac_types),
        "ride_status": random.choice(ride_status),
        "distance_km": distance_km, 
        "fare": total_fare, 
        "booking_time": fake.date_time_between(start_date=start_date, end_date=end_date),
    })

progress_start = time.time()    # Start progress timer before generating records
for i in range (100000):
    data_generator()
    
    if i % 10000 == 0 and i != 0:  # Print progress every 10,000 records
        progress_end = time.time() 
        print(f"Generated {i} records in {progress_end - progress_start:.2f} seconds")
        progress_start = time.time()  # Reset progress timer after each 10,000 records

overall_end_time = time.time()
print(f"Data generation completed in {overall_end_time - overall_start_time:.2f} seconds")

df = pd.DataFrame(ride_booking)
print(df.head())'''

'import pandas as pd \nimport time\n\noverall_start_time = time.time()\nride_booking = []\n\ndef data_generator():\n    car_type = random.choice(car_types)\n    distance_km = round(random.uniform(1, 30), 2) # Distance between 1 and 30 km\n    total_fare = round(base_fare + fare_rates[car_type] * distance_km, 2) # Base fare + (rate per km * distance)\n    ride_booking.append({\n        "ride_id": fake.uuid4(),\n        "driver_name": fake.name(),\n        "driver_phone": fake.phone_number(),\n        "driver_rating": round(random.uniform(3.5, 5.0), 1), # Rating between 3.5 and 5.0\n        "driver_experience_years": random.randint(1, 20), # Experience between 1 and 20 years\n        "driver_vehicle_number": license_plate_generator(),\n        "driver_vehicle_model": random.choice(vehicle_models),\n        "customer_name": fake.name(),\n        "customer_phone": fake.phone_number(),  \n        "pickup_location": random.choice(mumbai_areas),\n        "drop_location": random.choice(mumbai_areas),\n        "car_type": car_type,\n        "fuel_type": random.choice(fuel_types),\n        "ac_type": random.choice(ac_types),\n        "ride_status": random.choice(ride_status),\n        "distance_km": distance_km, \n        "fare": total_fare, \n        "booking_time": fake.date_time_between(start_date=start_date, end_date=end_date),\n    })\n\nprogress_start = time.time()    # Start progress timer before generating records\nfor i in range (100000):\n    data_generator()\n\n    if i % 10000 == 0 and i != 0:  # Print progress every 10,000 records\n        progress_end = time.time() \n        print(f"Generated {i} records in {progress_end - progress_start:.2f} seconds")\n        progress_start = time.time()  # Reset progress timer after each 10,000 records\n\noverall_end_time = time.time()\nprint(f"Data generation completed in {overall_end_time - overall_start_time:.2f} seconds")\n\ndf = pd.DataFrame(ride_booking)\nprint(df.head())'

In [71]:
random_item = round(random.uniform(1, 30))
print(random_item)

9

## Unsderstanding of Timestamp DateOffset , datetime timedelta

In [72]:
'''current_date = pd.Timestamp.now(tz='UTC') 
start_date = current_date - pd.DateOffset(years=1)


print(f"Start Date: {start_date}")
print(f"Current Date: {current_date}")

india_time = current_date.tz_convert("Asia/Kolkata")

print(f"India Time: {india_time}")'''

'''start_date = datetime.now() -  timedelta(days=7)  # Generate data for the past 7 days
end_date = datetime.now()

print(start_date)
print(end_date) '''

'''start = pd.Timestamp("2026-05-25 00:00:00") - pd.DateOffset(years=1) # Generate data for the past 1 year / same month last year
now = pd.Timestamp.now()

print(start)
print(now)'''

'start = pd.Timestamp("2026-05-25 00:00:00") - pd.DateOffset(years=1) # Generate data for the past 1 year / same month last year\nnow = pd.Timestamp.now()\n\nprint(start)\nprint(now)'

# Sampling

List ---> Random    
DataFrame ----> Sampling

In [73]:
import random
df = pd.read_csv("../data/drivers.csv")
#Fraction sampling
df.sample(frac=0.5)         #50% data

,driver_id,driver_name,driver_phone,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
8028,DRV8029,Ati Kuruvilla,3029297424,MH35 TC 5288,Tata Nexon,SUV,4.1,4
2178,DRV2179,Samuel Rajagopalan,9901576784,MH18 LC 7011,Swift Dzire,Sedan,3.6,2
4517,DRV4518,Jacob Dora,5485352084,MH5 GI 4841,Tata Nexon,SUV,4.8,7
158,DRV0159,Mason Morar,914017148354,MH15 ZO 6447,Swift Dzire,Sedan,4.4,8
5163,DRV5164,Inaya Grover,6175961256,MH6 KO 2372,Swift Dzire,Sedan,4.2,2
...,...,...,...,...,...,...,...,...
5522,DRV5523,Manan Menon,1688206949,MH26 DE 1840,Swift Dzire,Sedan,4.7,16
308,DRV0309,Leela Wagle,912670975396,MH25 KE 7763,Honda City,Sedan,4.2,6
9395,DRV9396,Manbir Baria,4087191450,MH20 OC 6896,Swift Dzire,Sedan,4.2,16
4284,DRV4285,Ayushman Shanker,594620484,MH10 FC 8365,WagonR,Hatchback,4.7,3
9833,DRV9834,Thomas Khosla,134068675,MH11 BU 8067,Swift Dzire,Sedan,4.8,11

In [74]:
#Reproducible sampling    ----->  same output every run
df.sample(n=5 , random_state=42)        #the randomness seed

,driver_id,driver_name,driver_phone,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
6252,DRV6253,Anay Kakar,911073496900,MH9 UX 1757,Tata Nexon,SUV,3.8,20
4684,DRV4685,Siddharth Uppal,914766538413,MH37 MM 6191,Honda City,Sedan,4.1,15
1731,DRV1732,Harsh Korpal,911902748606,MH43 NW 1296,Tata Nexon,SUV,3.9,9
4742,DRV4743,Aayush Buch,5610829074,MH22 OI 9508,Tata Nexon,SUV,4.0,5
4521,DRV4522,Gauri Nazareth,3117255674,MH22 IL 9957,Toyota Innova,SUV,3.7,5

In [75]:
import random

random.seed(2)
print(random.randint(1,10))

1

In [76]:
df.sample(n=5)

,driver_id,driver_name,driver_phone,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
1519,DRV1520,Chaitanya Sahni,8244366076,MH35 CD 0953,Tata Nexon,SUV,5.0,5
812,DRV0813,Brinda Chaudhary,2353700252,MH23 OZ 1761,Hyundai Creta,SUV,4.7,13
6903,DRV6904,Pranit Soni,918968345749,MH12 JL 2846,Swift Dzire,Sedan,4.4,4
1453,DRV1454,Bina Gaba,8202351021,MH36 EU 3465,Hyundai Creta,SUV,4.5,19
4980,DRV4981,Rachana Saini,6367359100,MH36 FF 3010,Toyota Innova,SUV,3.8,12

In [77]:
import random

df.sample(n=random.randint(1,5))

,driver_id,driver_name,driver_phone,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
3988,DRV3989,Timothy Chand,3874424608,MH17 AT 5552,Honda City,Sedan,4.0,15

In [91]:
import random

row = df.sample(n=5)
row

,driver_id,driver_name,driver_phone,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
9031,DRV9032,Vasudha Gulati,910029630295,MH25 WC 0105,Hyundai Creta,SUV,4.4,2
7333,DRV7334,Dalbir Batra,910396245862,MH27 ZK 0813,Tata Nexon,SUV,3.6,1
1699,DRV1700,Gopal Kar,917881646296,MH30 EY 9210,Toyota Innova,SUV,3.9,9
5019,DRV5020,Ranveer Dutt,2833022997,MH44 UO 3475,Toyota Innova,SUV,4.4,4
746,DRV0747,Ria Srinivasan,919958972941,MH36 GN 0291,Swift Dzire,Sedan,4.5,18

In [92]:
row.to_dict()       # nested dictionary

{'driver_id': {9031: 'DRV9032',
  7333: 'DRV7334',
  1699: 'DRV1700',
  5019: 'DRV5020',
  746: 'DRV0747'},
 'driver_name': {9031: 'Vasudha Gulati',
  7333: 'Dalbir Batra',
  1699: 'Gopal Kar',
  5019: 'Ranveer Dutt',
  746: 'Ria Srinivasan'},
 'driver_phone': {9031: 910029630295,
  7333: 910396245862,
  1699: 917881646296,
  5019: 2833022997,
  746: 919958972941},
 'license_plate': {9031: 'MH25 WC 0105',
  7333: 'MH27 ZK 0813',
  1699: 'MH30 EY 9210',
  5019: 'MH44 UO 3475',
  746: 'MH36 GN 0291'},
 'driver_vehicle_model': {9031: 'Hyundai Creta',
  7333: 'Tata Nexon',
  1699: 'Toyota Innova',
  5019: 'Toyota Innova',
  746: 'Swift Dzire'},
 'car_type': {9031: 'SUV',
  7333: 'SUV',
  1699: 'SUV',
  5019: 'SUV',
  746: 'Sedan'},
 'driver_rating': {9031: 4.4, 7333: 3.6, 1699: 3.9, 5019: 4.4, 746: 4.5},
 'driver_experience_years': {9031: 2, 7333: 1, 1699: 9, 5019: 4, 746: 18}}

In [100]:
row['driver_name'][7333]

'Dalbir Batra'

In [94]:
row['driver_name']

9031    Vasudha Gulati
7333      Dalbir Batra
1699         Gopal Kar
5019      Ranveer Dutt
746     Ria Srinivasan
Name: driver_name, dtype: str

In [ ]:
row.iloc[0].to_dict()       # ONE row(Series)  ,  column → value

{'driver_id': 'DRV9032',
 'driver_name': 'Vasudha Gulati',
 'driver_phone': 910029630295,
 'license_plate': 'MH25 WC 0105',
 'driver_vehicle_model': 'Hyundai Creta',
 'car_type': 'SUV',
 'driver_rating': 4.4,
 'driver_experience_years': 2}

In [ ]:
# Why weird indexes like 7333?
# df.sample() -----> keeps original dataframe indexes.
# for clean indexing ----> row.iloc[1:4].reset_index(drop=True)

row.iloc[1:4].to_dict()         # MULTIPLE rows(DataFrame)----> column → {index:value}

{'driver_id': {7333: 'DRV7334', 1699: 'DRV1700', 5019: 'DRV5020'},
 'driver_name': {7333: 'Dalbir Batra',
  1699: 'Gopal Kar',
  5019: 'Ranveer Dutt'},
 'driver_phone': {7333: 910396245862, 1699: 917881646296, 5019: 2833022997},
 'license_plate': {7333: 'MH27 ZK 0813',
  1699: 'MH30 EY 9210',
  5019: 'MH44 UO 3475'},
 'driver_vehicle_model': {7333: 'Tata Nexon',
  1699: 'Toyota Innova',
  5019: 'Toyota Innova'},
 'car_type': {7333: 'SUV', 1699: 'SUV', 5019: 'SUV'},
 'driver_rating': {7333: 3.6, 1699: 3.9, 5019: 4.4},
 'driver_experience_years': {7333: 1, 1699: 9, 5019: 4}}

In [107]:
row.iloc[1:4].to_dict(orient="records")

[{'driver_id': 'DRV7334',
  'driver_name': 'Dalbir Batra',
  'driver_phone': 910396245862,
  'license_plate': 'MH27 ZK 0813',
  'driver_vehicle_model': 'Tata Nexon',
  'car_type': 'SUV',
  'driver_rating': 3.6,
  'driver_experience_years': 1},
 {'driver_id': 'DRV1700',
  'driver_name': 'Gopal Kar',
  'driver_phone': 917881646296,
  'license_plate': 'MH30 EY 9210',
  'driver_vehicle_model': 'Toyota Innova',
  'car_type': 'SUV',
  'driver_rating': 3.9,
  'driver_experience_years': 9},
 {'driver_id': 'DRV5020',
  'driver_name': 'Ranveer Dutt',
  'driver_phone': 2833022997,
  'license_plate': 'MH44 UO 3475',
  'driver_vehicle_model': 'Toyota Innova',
  'car_type': 'SUV',
  'driver_rating': 4.4,
  'driver_experience_years': 4}]