## Genrerating realistic fake database using `FAKER` librabry

In [18]:
import pandas as pd 
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker('en_IN') # Use Indian locale for realistic data

In [19]:
mumbai_areas = ['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Ghatkopar', 'Juhu', 'Kurla', 'Malad', 'Mulund', 'Powai', 'Santacruz', 'Vile Parle']
car_types = ['Sedan', 'SUV', 'Hatchback']
fuel_types = ['Petrol', 'Diesel', 'Electric', 'Hybrid']
ac_types = ["Ac", "Non-Ac"]
ride_status = ["Completed", "Completed", "Completed", "Completed", "Cancelled"] # 80% completed, 20% cancelled

In [20]:
'''print(f"Mumbai Areas: {mumbai_areas}")
print(f"Car Types: {car_types}")
print(f"Fuel Types: {fuel_types}")
print(f"AC Types: {ac_types}")
print(f"Ride Status: {ride_status}")
print(f"Vehicle Models: {vehicle_models}")'''

'print(f"Mumbai Areas: {mumbai_areas}")\nprint(f"Car Types: {car_types}")\nprint(f"Fuel Types: {fuel_types}")\nprint(f"AC Types: {ac_types}")\nprint(f"Ride Status: {ride_status}")\nprint(f"Vehicle Models: {vehicle_models}")'

# Pay by car type and base pay

In [21]:
fare_rates = {
  "Sedan" : 15,
  "SUV" : 19,
  "Hatchback" : 11
}
base_fare = 50

## Data from past 1 year

In [22]:
end_date = datetime.now()
start_date = end_date - timedelta(days=365) # Last 1 year

print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")

Start Date: 2025-06-02 21:40:45.421664
End Date: 2026-06-02 21:40:45.421664

## Generating and storing unique Licence plate numbeer

In [23]:
import pandas as pd 
import random
import string 
import time 

start_rand_plate_num = time.time()
used_numbers = set()       #  set  → validation / lookup (fast checking)
plates = []                   # list → storage / ordering (ordered storage)

def license_plate_generator():
    state = 'MH' # Maharashtra state code for license plates
    district_code = random.randint(1, 50) # Random district code between 1 and 50

    letters = string.ascii_uppercase # Uppercase letters for license plate
    char = ''.join(random.choices(letters, k=2)) # Random 2 letters for license plate

    numeric_part = f"{random.randint(0, 9999):04d}" # Random 4 digit number for license plate, formated 04d means fill empty space with 0 and generate 4 digit number d means integer
    return f"{state}{district_code} {char} {numeric_part}"

end_rand_plate_num = time.time()

start_unique_plate = time.time()

def generate_unique_license_plate():
    while True:
        license_plate = license_plate_generator()
        if license_plate not in used_numbers:
            used_numbers.add(license_plate)
            plates.append(license_plate)        # just to create a list to check

            return license_plate

for i in range(10000):
        vehicle_license_plate = generate_unique_license_plate()
        
end_unique_plate = time.time()

print(f"Random plate generated : {end_rand_plate_num - start_rand_plate_num:.2}") 
time.sleep(1)
print(f"Unique plate identified and stored: {end_unique_plate - start_unique_plate:.2}\n")
time.sleep(1)

print(f"Generated License Plate: {vehicle_license_plate}")
time.sleep(1)
print(f"Unique plate numbers: {(plates)[-5:]}")        # last 5 plate numbers
time.sleep(1)
print(f"Total num of unique plates generated: {len(used_numbers)} ")
time.sleep(1)

df = pd.DataFrame

Random plate generated : 0.0
Unique plate identified and stored: 0.027

Generated License Plate: MH19 KH 9540
Unique plate numbers: ['MH1 BD 7041', 'MH40 AQ 9534', 'MH23 JI 7686', 'MH21 HM 5011', 'MH19 KH 9540']
Total num of unique plates generated: 10000

In [24]:
print(len(vehicle_license_plate)) # counts the characte of the plates

12

# Generating 10000 unique drivers data

In [25]:
vehicle_category = {

    "Hyundai Creta": "SUV",

    "Tata Nexon": "SUV",

    "Honda City": "Sedan",

    "Swift Dzire": "Sedan",

    "WagonR": "Hatchback",

    "Toyota Innova": "SUV"
}

# idempotency
Running the same code multiple times should not corrupt or change existing valid data.

In [26]:
import pandas as pd 
import random 
from faker import Faker 
import time

faker = Faker('en_IN')  

# idempotency
import os

if not os.path.exists("../data/drivers.csv"):   # Check if file exists if yes True ---> Fale (reverse result)
    print("Generating new drivers...")
    
    driver_info = []
    letters = 'DRV'

    def drivers_data(driver_num):
        vehical_model = random.choice(list(vehicle_category.keys()))
        joining_date = pd.Timestamp('2011-01-01')
        current_date = datetime.now()
        driver_info.append({
            "driver_id" : f"{letters}{driver_num+1:05d}",
            "driver_name" : faker.name(),
            "driver_phone": faker.phone_number(),
            "driver_age": random.randint(18,70),
            "driver_address": f"Flat {random.randint(1,500)}, {random.choice(mumbai_areas)}",
            "registration_date": faker.date_time_between(joining_date, current_date),
            "license_plate" : plates[driver_num],
            "driver_vehicle_model": vehical_model,  
            "car_type": vehicle_category[vehical_model],        # dictonary lookup
            "driver_rating": round(random.uniform(3.5, 5.0), 1), # Rating between 3.5 and 5.0
            "driver_experience_years": random.randint(1, 20), # Experience between 1 and 20 years
        })

    for driver_num in range(10000):
        drivers_data(driver_num)

    df = pd.DataFrame(driver_info)
    df.index = range(1,len(df) + 1)

    df.to_csv("../data/drivers.csv" , sep = ",", index=False )

else:
    print("Drivers already exist")
    df = pd.read_csv("../data/drivers.csv")
df

Generating new drivers...

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
1,DRV00001,Chandran Krishnamurthy,+912651324548,40,"Flat 256, Santacruz",2026-03-03 21:57:54,MH7 SR 6171,Honda City,Sedan,3.9,14
2,DRV00002,Kashvi Dhar,3447817582,44,"Flat 205, Powai",2011-07-08 22:25:03,MH43 TF 5312,Swift Dzire,Sedan,4.2,9
3,DRV00003,Darika Memon,05828772379,24,"Flat 428, Santacruz",2012-10-22 08:59:19,MH23 EM 0917,WagonR,Hatchback,4.8,17
4,DRV00004,Jagdish Pandya,+910159393518,65,"Flat 40, Borivali",2016-10-03 22:54:43,MH5 LU 6646,Swift Dzire,Sedan,4.5,9
5,DRV00005,Unnati Modi,09341674007,70,"Flat 478, Powai",2012-10-05 22:20:16,MH2 OY 5574,Tata Nexon,SUV,4.2,16
...,...,...,...,...,...,...,...,...,...,...,...
9996,DRV09996,Azaan Sarma,+914355898887,50,"Flat 268, Mulund",2015-06-07 12:08:33,MH1 BD 7041,Swift Dzire,Sedan,3.5,15
9997,DRV09997,Arya Dhillon,0927586309,33,"Flat 197, Vile Parle",2012-03-26 19:45:13,MH40 AQ 9534,Tata Nexon,SUV,4.8,5
9998,DRV09998,Jacob Mander,+911896030247,43,"Flat 7, Kurla",2016-03-09 23:48:02,MH23 JI 7686,Tata Nexon,SUV,4.9,16
9999,DRV09999,Girindra Lad,6451264487,27,"Flat 184, Bandra",2025-09-03 01:39:20,MH21 HM 5011,Tata Nexon,SUV,4.3,13
10000,DRV10000,Zilmil Kunda,3233306135,69,"Flat 127, Santacruz",2020-08-02 06:54:33,MH19 KH 9540,Hyundai Creta,SUV,4.9,6

In [27]:
random_item = round(random.uniform(1, 30))
print(random_item)

4

# Sampling

List ---> Random    
DataFrame ----> Sampling

In [28]:
import random
df = pd.read_csv("../data/drivers.csv")
#Fraction sampling
df.sample(frac=0.5)         #50% data

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
1090,DRV01091,Diya Upadhyay,987407183,33,"Flat 218, Dadar",2021-03-15 17:36:56,MH9 WH 9170,Toyota Innova,SUV,4.1,4
4810,DRV04811,Idika Joshi,5193182004,69,"Flat 268, Santacruz",2019-06-24 01:32:01,MH38 SI 3221,Honda City,Sedan,4.8,9
2431,DRV02432,Chatura Bajwa,916548320801,34,"Flat 108, Juhu",2016-05-09 14:32:45,MH8 VR 8879,WagonR,Hatchback,3.5,14
8021,DRV08022,Vyanjana Karan,8160854752,40,"Flat 172, Malad",2021-09-23 01:12:56,MH48 EZ 0717,Toyota Innova,SUV,3.7,18
8261,DRV08262,Jhalak Sangha,2504656194,60,"Flat 476, Bandra",2012-09-01 20:47:36,MH28 FV 2949,WagonR,Hatchback,4.5,1
...,...,...,...,...,...,...,...,...,...,...,...
8575,DRV08576,Dhriti Ramesh,1913993705,43,"Flat 303, Powai",2020-04-27 16:55:21,MH37 QC 8264,Swift Dzire,Sedan,4.7,7
5547,DRV05548,Geetika Soni,6270556868,27,"Flat 238, Ghatkopar",2021-12-28 21:54:08,MH1 AJ 8707,WagonR,Hatchback,3.6,19
1531,DRV01532,Mahika Sidhu,4673644896,65,"Flat 358, Andheri",2023-10-14 07:24:09,MH44 LX 2955,Honda City,Sedan,3.6,17
6478,DRV06479,Shivani Grewal,1964185771,31,"Flat 398, Mulund",2017-04-05 10:03:03,MH27 AD 7675,Toyota Innova,SUV,3.9,20
1821,DRV01822,Hamsini Nagarajan,918064182327,56,"Flat 150, Santacruz",2025-01-23 07:38:46,MH48 GE 8007,WagonR,Hatchback,4.6,7

In [29]:
#Reproducible sampling    ----->  same output every run
df.sample(n=5 , random_state=42)        #the randomness seed

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
6252,DRV06253,Hritik Rai,891070740,64,"Flat 181, Powai",2018-08-25 20:40:10,MH50 SU 6778,Swift Dzire,Sedan,4.9,1
4684,DRV04685,Sara Rastogi,7264567256,68,"Flat 274, Powai",2016-08-12 10:38:52,MH17 UA 1497,Hyundai Creta,SUV,4.3,14
1731,DRV01732,Kritika Mallick,918518550079,32,"Flat 365, Santacruz",2014-09-17 14:22:36,MH32 BT 9974,Toyota Innova,SUV,3.8,17
4742,DRV04743,Theodore Dutta,3078224999,38,"Flat 100, Vile Parle",2020-03-30 18:38:49,MH15 BG 0383,Tata Nexon,SUV,3.8,17
4521,DRV04522,Falak Barman,918469167197,48,"Flat 317, Powai",2019-05-30 05:51:28,MH39 UN 8837,WagonR,Hatchback,4.7,12

In [30]:
import random

random.seed(2)
print(random.randint(1,10))

1

In [31]:
df.sample(n=5)

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
7611,DRV07612,Deepa Singhal,917319084991,46,"Flat 12, Juhu",2020-05-28 06:27:16,MH13 PI 3905,Tata Nexon,SUV,3.6,20
9533,DRV09534,Aarini Johal,915298073771,26,"Flat 162, Borivali",2014-04-12 20:02:02,MH3 YB 1374,Swift Dzire,Sedan,3.6,7
2736,DRV02737,Maanas Dasgupta,813951586,23,"Flat 161, Ghatkopar",2013-10-26 16:42:17,MH27 AD 9004,Hyundai Creta,SUV,4.7,13
8440,DRV08441,Leela Ghose,911278176996,25,"Flat 38, Andheri",2026-03-03 11:14:47,MH6 MX 2935,Toyota Innova,SUV,3.7,9
8728,DRV08729,Bhavya Nori,910625085243,43,"Flat 335, Borivali",2013-03-21 15:21:07,MH23 KU 0185,WagonR,Hatchback,4.5,5

In [32]:
import random

df.sample(n=random.randint(1,5))

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
888,DRV00889,Gautam Anand,7775642969,62,"Flat 119, Andheri",2026-04-20 09:24:43,MH4 YN 8403,Toyota Innova,SUV,4.2,4

# Converting datafram sample to `dictionary`

In [33]:
df_drivers = df.sample(n=5)
df_drivers.to_dict()       # nested dictionary

'''df_drivers['driver_name'][7333]  
df_drivers['driver_name']'''
df_drivers.iloc[0].to_dict()       # ONE rows(Series)  ,  column → value

{'driver_id': 'DRV06977',
 'driver_name': 'Sanaya Setty',
 'driver_phone': 5848269511,
 'driver_age': 58,
 'driver_address': 'Flat 465, Dadar',
 'registration_date': '2021-09-12 20:48:18',
 'license_plate': 'MH23 UN 9483',
 'driver_vehicle_model': 'WagonR',
 'car_type': 'Hatchback',
 'driver_rating': 4.3,
 'driver_experience_years': 8}

In [34]:
df_drivers.iloc[1:4].to_dict()         # MULTIPLE ds(DataFrame)----> column → {index:value}

{'driver_id': {5217: 'DRV05218', 7135: 'DRV07136', 208: 'DRV00209'},
 'driver_name': {5217: 'Vincent Nair',
  7135: 'Aarav Ahuja',
  208: 'Sarthak Jhaveri'},
 'driver_phone': {5217: 8289821519, 7135: 4089681228, 208: 8900824917},
 'driver_age': {5217: 61, 7135: 48, 208: 22},
 'driver_address': {5217: 'Flat 138, Mulund',
  7135: 'Flat 353, Juhu',
  208: 'Flat 451, Dadar'},
 'registration_date': {5217: '2019-11-30 21:33:28',
  7135: '2013-06-20 04:17:51',
  208: '2011-09-23 01:46:27'},
 'license_plate': {5217: 'MH8 OP 4639',
  7135: 'MH4 TD 5733',
  208: 'MH5 GG 2877'},
 'driver_vehicle_model': {5217: 'Toyota Innova',
  7135: 'Swift Dzire',
  208: 'Toyota Innova'},
 'car_type': {5217: 'SUV', 7135: 'Sedan', 208: 'SUV'},
 'driver_rating': {5217: 3.7, 7135: 4.3, 208: 5.0},
 'driver_experience_years': {5217: 6, 7135: 20, 208: 20}}

In [35]:
# Why weird indexes like 7333?
# df.sample() -----> keeps original dataframe indexes.
# for clean indexing ----> row.iloc[1:4].reset_index(drop=True)  

'''import random

d = df.sample(n=5)
d.iloc[1:5].reset_index(drop=True).to_dict()'''

df_drivers.iloc[1:4].to_dict(orient="records")

[{'driver_id': 'DRV05218',
  'driver_name': 'Vincent Nair',
  'driver_phone': 8289821519,
  'driver_age': 61,
  'driver_address': 'Flat 138, Mulund',
  'registration_date': '2019-11-30 21:33:28',
  'license_plate': 'MH8 OP 4639',
  'driver_vehicle_model': 'Toyota Innova',
  'car_type': 'SUV',
  'driver_rating': 3.7,
  'driver_experience_years': 6},
 {'driver_id': 'DRV07136',
  'driver_name': 'Aarav Ahuja',
  'driver_phone': 4089681228,
  'driver_age': 48,
  'driver_address': 'Flat 353, Juhu',
  'registration_date': '2013-06-20 04:17:51',
  'license_plate': 'MH4 TD 5733',
  'driver_vehicle_model': 'Swift Dzire',
  'car_type': 'Sedan',
  'driver_rating': 4.3,
  'driver_experience_years': 20},
 {'driver_id': 'DRV00209',
  'driver_name': 'Sarthak Jhaveri',
  'driver_phone': 8900824917,
  'driver_age': 22,
  'driver_address': 'Flat 451, Dadar',
  'registration_date': '2011-09-23 01:46:27',
  'license_plate': 'MH5 GG 2877',
  'driver_vehicle_model': 'Toyota Innova',
  'car_type': 'SUV',
  'driver_rating': 5.0,
  'driver_experience_years': 20}]

# Customer Data Generation

In [36]:
import pandas as pd
import random
import string
from faker import Faker
import time

faker = Faker('en_IN')
# idempotency
import os 

if not os.path.exists("../data/customer.csv"):
    print("Generating new customer data..")

    customer_info = []
    #char = ''.join(random.choices(letters , k=2))

    def customer_data(i):
        joining_date = pd.Timestamp("2011-01-01")
        current_date = datetime.now()
        customer_info.append({
            'customer_id': f"CUS{i+1:05d}",
            'customer_name': faker.name(),
            'customer_phone': faker.phone_number(),
            'customer_age': random.randint(18,60),
            'customer_address': f"Flat {random.randint(1,500)}, {random.choice(mumbai_areas)}",
            "registration_date": faker.date_time_between(joining_date ,current_date),
        })

    for i in range(50000):
        customer_data(i)

    df = pd.DataFrame(customer_info)
    df.index = range(1,len(df) +1)
    df.to_csv("../data/customer.csv",index=False)

else:
    print('Data already exisit.')
    df = pd.read_csv("../data/customer.csv")
df

Generating new customer data..

,customer_id,customer_name,customer_phone,customer_age,customer_address,registration_date
1,CUS00001,Hema Chokshi,6130194192,23,"Flat 185, Borivali",2017-10-04 04:56:39
2,CUS00002,Yadavi Dave,02720046701,60,"Flat 438, Ghatkopar",2013-06-25 14:17:27
3,CUS00003,Ekansh Nigam,07445644364,34,"Flat 311, Dadar",2024-02-14 12:55:58
4,CUS00004,Suhani Lalla,5372925331,56,"Flat 19, Powai",2011-05-15 20:09:45
5,CUS00005,Rohan Raval,8860777114,28,"Flat 221, Santacruz",2018-04-13 20:55:29
...,...,...,...,...,...,...
49996,CUS49996,Reva Sundaram,7869523289,23,"Flat 409, Bandra",2017-08-16 19:51:59
49997,CUS49997,Ayush Ratta,3350407214,45,"Flat 492, Vile Parle",2015-07-08 14:56:53
49998,CUS49998,Atharv Wason,+918831690299,29,"Flat 233, Malad",2019-09-21 15:03:30
49999,CUS49999,Chakradhar Bumb,07102699247,39,"Flat 84, Juhu",2014-07-15 02:28:25
50000,CUS50000,Manthan Bansal,+912363264023,59,"Flat 456, Powai",2015-12-04 17:02:40

## Unsderstanding of Timestamp DateOffset , datetime timedelta

In [37]:
# Timestamp WHEN?? --> an exact point in time                                       eg 2026-05-29 18:30:00                 "ride start time/customer register time"
# Timedelta(thinks in exact units) HOW LONG???--> a duration(24 hours exactly)          eg 2 days / 3 hr / 30 min              "delivery time/exact hr min"
# DateOffset MOVE ON CALENDAR--> calendar-based movement                                     eg 1 month later / 1 year ago          "next month/previous year"
'''🚗 Important
DateOffset understands:
leap years
month lengths
calendars'''
# datetime --> basic Python date object

'''current_date = pd.Timestamp.now(tz='UTC') 
start_date = current_date - pd.DateOffset(years=1)


print(f"Start Date: {start_date}")
print(f"Current Date: {current_date}")

india_time = current_date.tz_convert("Asia/Kolkata")

print(f"India Time: {india_time}")'''

start_date = datetime.now() -  timedelta(days=7)  # Generate data for the past 7 days
end_date = datetime.now()

print(start_date)
print(end_date) 

#start = pd.Timestamp("2026-05-25 00:00:00") + pd.DateOffset(years=1) # Generate data for the future 1 year / same month last year
#now = pd.Timestamp.now()

#print(start)
#print(now)

2026-05-26 21:40:52.901175
2026-06-02 21:40:52.901175

# Rides Data Generation

In [38]:
import pandas as pd
import random
from faker import Faker
import time

faker = Faker('en_IN')

import os 

if not os.path.exists("../data/rides_data.csv"):
    print("Generating new rides data..")

    start_time = time.time()

    rides = []

    # placing these above line outside the function so that they dont decrease performance speed
    driver = pd.read_csv("../data/drivers.csv")
    customer = pd.read_csv("../data/customer.csv")

    driver_list = driver.to_dict(orient="records")
    customer_list = customer.to_dict(orient="records")

    start_date = datetime.now() - timedelta(days=365)
    end_date = datetime.now()

    def ride_generator(i):
        # drivers data in dictionary form
        driver_dict = random.choice(driver_list)
        customer_dict = random.choice(customer_list)

        distance_km = round(random.uniform(1, 30), 2) # Distance between 1 and 30 km
        car_type = driver_dict["car_type"]
        rate_per_km = round(fare_rates[car_type],2)
        total_fare = round(base_fare + rate_per_km * distance_km, 2) # Base fare + (rate per km * distance)
        
        # pickup and drop time
        pickup = faker.date_time_between(start_date , end_date)  # past 1 year time
        drop = pickup + timedelta(minutes=random.randint(20,90))    

        duration = drop - pickup
        
        # unique pickup and drop locations 
        pickup_location = random.choice(mumbai_areas)
        drop_location = random.choice(mumbai_areas)
        while pickup_location == drop_location:
            drop_location = random.choice(mumbai_areas)

        rides.append({
            'ride_id': f"RID{i+1:06d}",
            'driver_id':driver_dict["driver_id"],
            'customer_id':customer_dict["customer_id"],
            'car_type': car_type,
            'pick_up_location': pickup_location,
            'drop_location': drop_location,
            'pickup_time': pickup,
            'drop_time': drop,
            'total_duration': duration.seconds //60,    
            'distance': distance_km,
            'rate_per_km': rate_per_km,
            'fare': total_fare,
            'ride_status': random.choice(['completed','completed','completed','completed','cancelled']),
        })

    for i in range(100000):
        ride_generator(i)

    end_time = time.time()

    df = pd.DataFrame(rides)
    df.index = range(1,len(df) +1)

    df.to_csv("../data/rides_data.csv", index=False)

    print(f"Data Generation Complete. {end_time - start_time}")

else:
    print("Data already exists.")
    df = pd.read_csv("../data/rides_data.csv")
df

Generating new rides data..
Data Generation Complete. 1.6395487785339355

,ride_id,driver_id,customer_id,car_type,pick_up_location,drop_location,pickup_time,drop_time,total_duration,distance,rate_per_km,fare,ride_status
1,RID000001,DRV01573,CUS44170,SUV,Kurla,Vile Parle,2026-01-24 05:49:50,2026-01-24 06:37:50,48,4.22,19,130.18,completed
2,RID000002,DRV05843,CUS15467,Sedan,Kurla,Malad,2026-03-26 17:42:21,2026-03-26 18:30:21,48,19.18,15,337.70,completed
3,RID000003,DRV04024,CUS23767,Sedan,Borivali,Santacruz,2025-07-22 20:27:30,2025-07-22 21:26:30,59,17.63,15,314.45,completed
4,RID000004,DRV01069,CUS19418,Sedan,Dadar,Bandra,2025-10-16 08:58:33,2025-10-16 09:42:33,44,1.71,15,75.65,completed
5,RID000005,DRV08292,CUS02496,Sedan,Vile Parle,Andheri,2026-05-15 12:41:39,2026-05-15 14:05:39,84,9.76,15,196.40,completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,RID099996,DRV02707,CUS32395,Sedan,Powai,Vile Parle,2025-09-20 17:40:46,2025-09-20 18:57:46,77,4.59,15,118.85,completed
99997,RID099997,DRV09183,CUS35713,SUV,Kurla,Bandra,2025-07-04 08:48:39,2025-07-04 09:33:39,45,19.39,19,418.41,completed
99998,RID099998,DRV06235,CUS04404,SUV,Bandra,Borivali,2025-12-11 14:57:11,2025-12-11 16:26:11,89,5.79,19,160.01,completed
99999,RID099999,DRV08543,CUS24848,SUV,Malad,Santacruz,2026-02-23 22:36:12,2026-02-23 23:21:12,45,6.09,19,165.71,completed
100000,RID100000,DRV07806,CUS21843,Hatchback,Bandra,Powai,2025-09-04 05:18:40,2025-09-04 06:37:40,79,9.12,11,150.32,completed

In [39]:
# for HH:MM:SS data " ".join(str(duration).split(" "))

In [40]:
df = pd.read_csv("../data/drivers.csv")
df

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
0,DRV00001,Chandran Krishnamurthy,912651324548,40,"Flat 256, Santacruz",2026-03-03 21:57:54,MH7 SR 6171,Honda City,Sedan,3.9,14
1,DRV00002,Kashvi Dhar,3447817582,44,"Flat 205, Powai",2011-07-08 22:25:03,MH43 TF 5312,Swift Dzire,Sedan,4.2,9
2,DRV00003,Darika Memon,5828772379,24,"Flat 428, Santacruz",2012-10-22 08:59:19,MH23 EM 0917,WagonR,Hatchback,4.8,17
3,DRV00004,Jagdish Pandya,910159393518,65,"Flat 40, Borivali",2016-10-03 22:54:43,MH5 LU 6646,Swift Dzire,Sedan,4.5,9
4,DRV00005,Unnati Modi,9341674007,70,"Flat 478, Powai",2012-10-05 22:20:16,MH2 OY 5574,Tata Nexon,SUV,4.2,16
...,...,...,...,...,...,...,...,...,...,...,...
9995,DRV09996,Azaan Sarma,914355898887,50,"Flat 268, Mulund",2015-06-07 12:08:33,MH1 BD 7041,Swift Dzire,Sedan,3.5,15
9996,DRV09997,Arya Dhillon,927586309,33,"Flat 197, Vile Parle",2012-03-26 19:45:13,MH40 AQ 9534,Tata Nexon,SUV,4.8,5
9997,DRV09998,Jacob Mander,911896030247,43,"Flat 7, Kurla",2016-03-09 23:48:02,MH23 JI 7686,Tata Nexon,SUV,4.9,16
9998,DRV09999,Girindra Lad,6451264487,27,"Flat 184, Bandra",2025-09-03 01:39:20,MH21 HM 5011,Tata Nexon,SUV,4.3,13
9999,DRV10000,Zilmil Kunda,3233306135,69,"Flat 127, Santacruz",2020-08-02 06:54:33,MH19 KH 9540,Hyundai Creta,SUV,4.9,6

In [41]:
list(df.columns)

['driver_id',
 'driver_name',
 'driver_phone',
 'driver_age',
 'driver_address',
 'registration_date',
 'license_plate',
 'driver_vehicle_model',
 'car_type',
 'driver_rating',
 'driver_experience_years']

In [42]:
import pandas as pd
df = pd.read_csv("../data/customer.csv")
df.head(2)

,customer_id,customer_name,customer_phone,customer_age,customer_address,registration_date
0,CUS00001,Hema Chokshi,6130194192,23,"Flat 185, Borivali",2017-10-04 04:56:39
1,CUS00002,Yadavi Dave,2720046701,60,"Flat 438, Ghatkopar",2013-06-25 14:17:27

In [43]:
list(df.columns)

['customer_id',
 'customer_name',
 'customer_phone',
 'customer_age',
 'customer_address',
 'registration_date']

In [44]:
df = pd.read_csv("../data/rides_data.csv")
df.head(2)

,ride_id,driver_id,customer_id,car_type,pick_up_location,drop_location,pickup_time,drop_time,total_duration,distance,rate_per_km,fare,ride_status
0,RID000001,DRV01573,CUS44170,SUV,Kurla,Vile Parle,2026-01-24 05:49:50,2026-01-24 06:37:50,48,4.22,19,130.18,completed
1,RID000002,DRV05843,CUS15467,Sedan,Kurla,Malad,2026-03-26 17:42:21,2026-03-26 18:30:21,48,19.18,15,337.70,completed

In [45]:
list(df.columns)

['ride_id',
 'driver_id',
 'customer_id',
 'car_type',
 'pick_up_location',
 'drop_location',
 'pickup_time',
 'drop_time',
 'total_duration',
 'distance',
 'rate_per_km',
 'fare',
 'ride_status']

In [46]:
df["fare"].dtype

dtype('float64')