In [1]:
from sqlalchemy import create_engine # helps create a connection engine that know which server and database to connect where it is (localhost etc) and also the username and password to authenticate
print("SQLAlchemy imported succesfully")

SQLAlchemy imported succesfully

# Connection String 
username : postgres (that's the default PostgreSQL username)    
password : whatever you set during installation  
host : localhost (your own machine)  
port : 5432 (PostgreSQL's default port)  
database name : mumbai_rides

In [2]:
#                    # database(type) "who you are"part  "where to go" part                                    
engine = create_engine("postgresql://postgres:admin123@localhost:5432/mumbai_rides")

The above is the connection string used to connect sqlachemy to postgresql it will get accepted if no error is thrown BUT   
The SqlAlchemy is lazy so the connection is only established when we actually use the engine    

To test the connection we can use the below line of code , it opens a connection stores the connection runs the code and exits (closes the connection)

In [3]:
with engine.connect() as connection:
    print("Connected to PostgreSQL successfully!")

Connected to PostgreSQL successfully!

### Base
Think of `Base` as:  `Database Blueprint Class`

It contains all SQLAlchemy functionality for:       
1.creating tables     
2.mapping classes to tables       
3.database metadata       
4.ORM operations    `ORM (Object Relational Mapper)`

In [4]:
from sqlalchemy import Column, String, Integer, Float, DateTime

In [5]:
# Defining Base (always needed before using Base)
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass    # Do nothing

In [6]:
# Sqlalchemy knows This class represents a database table. (because of Base)

class driver(Base):        # User inherits all database capabilities from Base.

    __tablename__ = "driver"       # Store data in a table called "driver"

    driver_id = Column(String , primary_key = True)
    driver_name = Column(String)
    driver_phone  = Column(String)
    driver_age = Column(Integer)
    driver_address = Column(String)
    registration_date = Column(DateTime)
    license_plate = Column(String)
    driver_vehicle_model = Column(String) 
    car_type = Column(String)
    driver_rating = Column(Float)
    driver_experience_years = Column(Integer)  

class customer(Base):   

    __tablename__ = "customer"

    customer_id = Column(String , primary_key = True) 
    customer_name   = Column(String)
    customer_phone  = Column(String)
    customer_age    = Column(Integer)
    customer_address    = Column(String)
    registration_date = Column(DateTime)

class rides(Base):

    __tablename__ = "rides"

    ride_id = Column(String, primary_key = True)
    driver_id = Column(String)      
    customer_id  = Column(String)
    car_type = Column(String)
    pick_up_location = Column(String)
    drop_location = Column(String)
    pickup_time  = Column(DateTime)
    drop_time = Column(DateTime)
    total_duration = Column(Integer)
    distance = Column(Float)
    rate_per_km  = Column(Float)
    fare = Column(Float)
    ride_status = Column(String)

In [7]:
Base.metadata.create_all(engine)    #registry of all the table classes
# it reads the Python classes and creates the actual tables in PostgreSQL.
print("Tables created successfully")

Tables created successfully

# Creating Session and loading the data

In [8]:
# Creating Session
from sqlalchemy.orm import Session

session = Session(engine)

In [9]:
import pandas as pd
df = pd.read_csv("../data/drivers.csv")         # Data Load
df.head(2)

,driver_id,driver_name,driver_phone,driver_age,driver_address,registration_date,license_plate,driver_vehicle_model,car_type,driver_rating,driver_experience_years
0,DRV00001,Chandran Krishnamurthy,912651324548,40,"Flat 256, Santacruz",2026-03-03 21:57:54,MH7 SR 6171,Honda City,Sedan,3.9,14
1,DRV00002,Kashvi Dhar,3447817582,44,"Flat 205, Powai",2011-07-08 22:25:03,MH43 TF 5312,Swift Dzire,Sedan,4.2,9

In [10]:
# # idempotency check : skip if data already exists
if session.query(driver).count() == 0:  
    print("Loading data in posgresql server...")
    drivers_list_of_dict = df.to_dict(orient="records")
    # load data
    session.bulk_insert_mappings(driver , drivers_list_of_dict)
    #session.rollback()      # to cancle the transaction
    session.commit()         # now it's permanent in PostgreSQL
else :
    print("Data already loaded")

Data already loaded

In [11]:
df = pd.read_csv("../data/customer.csv")
df.head(2)

,customer_id,customer_name,customer_phone,customer_age,customer_address,registration_date
0,CUS00001,Hema Chokshi,6130194192,23,"Flat 185, Borivali",2017-10-04 04:56:39
1,CUS00002,Yadavi Dave,2720046701,60,"Flat 438, Ghatkopar",2013-06-25 14:17:27

In [12]:

if session.query(customer).count() == 0:
    print("Loading data in posgresql server...")
    customer_list_dict = df.to_dict(orient="records")
    session.bulk_insert_mappings(customer , customer_list_dict)
    session.commit()
else:
    print("Data already loaded")

Data already loaded

In [13]:
df = pd.read_csv("../data/rides_data.csv")
df.head(2)

,ride_id,driver_id,customer_id,car_type,pick_up_location,drop_location,pickup_time,drop_time,total_duration,distance,rate_per_km,fare,ride_status
0,RID000001,DRV01573,CUS44170,SUV,Kurla,Vile Parle,2026-01-24 05:49:50,2026-01-24 06:37:50,48,4.22,19,130.18,completed
1,RID000002,DRV05843,CUS15467,Sedan,Kurla,Malad,2026-03-26 17:42:21,2026-03-26 18:30:21,48,19.18,15,337.70,completed

In [14]:
if session.query(rides).count() == 0:
    print("Loading data in posgresql server...")
    rides_list_dict = df.to_dict(orient="records")
    session.bulk_insert_mappings(rides , rides_list_dict)
    session.commit()
else:
    print("Data already loaded")

Data already loaded

In [18]:
result = session.query(rides).filter(rides.fare > 337).all()
print(len(result))
print(type(result))
print(result[0])

40026
<class 'list'>
<__main__.rides object at 0x000001A20470CFD0>

In [16]:
print(result[0].ride_id)
print(result[0].driver_id)
print(result[0].customer_id)

RID000002
DRV05843
CUS15467